apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2022-05-17T13:43:55Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: order-server
  name: order-server
  namespace: default
  resourceVersion: "224790"
  uid: 2704793f-6915-4c10-841c-cca8674cdde1
spec:
  clusterIP: 10.120.1.248
  clusterIPs:
  - 10.120.1.248
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32075
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: order-server
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.124.160.44